syntax = "proto3";

package member;

service MemberService {
  rpc ResolveShotParticipants(ResolveShotParticipantsRequest)
      returns (ResolveShotParticipantsResponse);

  rpc ResolveMemberNames(ResolveMemberNamesRequest)
      returns (ResolveMemberNamesResponse);

  rpc ResolveCurrentMember(ResolveCurrentMemberRequest)
      returns (ResolveCurrentMemberResponse);
}

message ResolveShotParticipantsRequest {
  string target_member_record_id = 1;
}

message ResolveShotParticipantsResponse {
  string from_id = 1;
  string to_id = 2;
}

message ResolveMemberNamesRequest {
  repeated string ids = 1;
}

message MemberName {
  string id = 1;
  string name = 2;
}

message ResolveMemberNamesResponse {
  repeated MemberName members = 1;
}

message ResolveCurrentMemberRequest {}

message ResolveCurrentMemberResponse {
  string id = 1;
}

service VideoService {
  rpc VerifyUploadedVideo(VerifyUploadedVideoRequest)
      returns (VerifyUploadedVideoResponse);

  rpc GetPostUpload(GetPostUploadRequest)
    returns (GetPostUploadResponse);

  rpc CompleteVideoUpload(CompleteVideoUploadRequest)
    returns (CompleteVideoUploadResponse);

}

message VerifyUploadedVideoRequest {
  string video_id = 1;
}

message VerifyUploadedVideoResponse {
  string video_id = 1;
}

message GetPostUploadRequest {
  string filename = 1;
  string content_type = 2;
  int64 size_bytes = 3;
}

message GetPostUploadResponse {
  string video_id = 1;
  string post_url = 2;
  map <string, string> form_data = 3;
}

message CompleteVideoUploadRequest {
  string video_id = 1;
}

message CompleteVideoUploadResponse {
  string video_id = 1;
}

