// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: member.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "member";

export interface ResolveShotParticipantsRequest {
  targetMemberRecordId: string;
}

export interface ResolveShotParticipantsResponse {
  fromId: string;
  toId: string;
}

export interface ResolveMemberNamesRequest {
  ids: string[];
}

export interface MemberName {
  id: string;
  name: string;
}

export interface ResolveMemberNamesResponse {
  members: MemberName[];
}

export interface ResolveCurrentMemberRequest {
}

export interface ResolveCurrentMemberResponse {
  id: string;
}

export interface ListShotTargetsRequest {
}

export interface ShotTarget {
  id: string;
  name: string;
  godname: string;
}

export interface ListShotTargetsResponse {
  members: ShotTarget[];
}

export const MEMBER_PACKAGE_NAME = "member";

export interface MemberServiceClient {
  resolveShotParticipants(
    request: ResolveShotParticipantsRequest,
    metadata?: Metadata,
  ): Observable<ResolveShotParticipantsResponse>;

  resolveMemberNames(request: ResolveMemberNamesRequest, metadata?: Metadata): Observable<ResolveMemberNamesResponse>;

  resolveCurrentMember(
    request: ResolveCurrentMemberRequest,
    metadata?: Metadata,
  ): Observable<ResolveCurrentMemberResponse>;

  listShotTargets(request: ListShotTargetsRequest, metadata?: Metadata): Observable<ListShotTargetsResponse>;
}

export interface MemberServiceController {
  resolveShotParticipants(
    request: ResolveShotParticipantsRequest,
    metadata?: Metadata,
  ): Observable<ResolveShotParticipantsResponse>;

  resolveMemberNames(request: ResolveMemberNamesRequest, metadata?: Metadata): Observable<ResolveMemberNamesResponse>;

  resolveCurrentMember(
    request: ResolveCurrentMemberRequest,
    metadata?: Metadata,
  ): Observable<ResolveCurrentMemberResponse>;

  listShotTargets(request: ListShotTargetsRequest, metadata?: Metadata): Observable<ListShotTargetsResponse>;
}

export function MemberServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "resolveShotParticipants",
      "resolveMemberNames",
      "resolveCurrentMember",
      "listShotTargets",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MemberService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MemberService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MEMBER_SERVICE_NAME = "MemberService";
