// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: member.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "member";

export interface ResolvePenaltyParticipantsRequest {
  targetMemberRecordId: string;
}

export interface ResolvePenaltyParticipantsResponse {
  fromId: string;
  toId: string;
}

export interface ResolveMemberNamesRequest {
  ids: string[];
}

export interface MemberName {
  id: string;
  name: string;
}

export interface ResolveMemberNamesResponse {
  members: MemberName[];
}

export interface ResolveCurrentMemberRequest {
}

export interface ResolveCurrentMemberResponse {
  id: string;
}

export interface ListPenaltyTargetsRequest {
}

export interface PenaltyTarget {
  id: string;
  name: string;
  godname: string;
}

export interface ListPenaltyTargetsResponse {
  members: PenaltyTarget[];
}

export const MEMBER_PACKAGE_NAME = "member";

export interface MemberServiceClient {
  resolvePenaltyParticipants(
    request: ResolvePenaltyParticipantsRequest,
    metadata?: Metadata,
  ): Observable<ResolvePenaltyParticipantsResponse>;

  resolveMemberNames(request: ResolveMemberNamesRequest, metadata?: Metadata): Observable<ResolveMemberNamesResponse>;

  resolveCurrentMember(
    request: ResolveCurrentMemberRequest,
    metadata?: Metadata,
  ): Observable<ResolveCurrentMemberResponse>;

  listPenaltyTargets(request: ListPenaltyTargetsRequest, metadata?: Metadata): Observable<ListPenaltyTargetsResponse>;
}

export interface MemberServiceController {
  resolvePenaltyParticipants(
    request: ResolvePenaltyParticipantsRequest,
    metadata?: Metadata,
  ): Observable<ResolvePenaltyParticipantsResponse>;

  resolveMemberNames(request: ResolveMemberNamesRequest, metadata?: Metadata): Observable<ResolveMemberNamesResponse>;

  resolveCurrentMember(
    request: ResolveCurrentMemberRequest,
    metadata?: Metadata,
  ): Observable<ResolveCurrentMemberResponse>;

  listPenaltyTargets(request: ListPenaltyTargetsRequest, metadata?: Metadata): Observable<ListPenaltyTargetsResponse>;
}

export function MemberServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "resolvePenaltyParticipants",
      "resolveMemberNames",
      "resolveCurrentMember",
      "listPenaltyTargets",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MemberService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MemberService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MEMBER_SERVICE_NAME = "MemberService";
