// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: video.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "video";

export interface VerifyUploadedVideoRequest {
  videoId: string;
}

export interface VerifyUploadedVideoResponse {
  videoId: string;
}

export interface GetPostUploadRequest {
  filename: string;
  contentType: string;
  sizeBytes: number;
}

export interface GetPostUploadResponse {
  videoId: string;
  postUrl: string;
  formData: { [key: string]: string };
}

export interface GetPostUploadResponse_FormDataEntry {
  key: string;
  value: string;
}

export interface CompleteVideoUploadRequest {
  videoId: string;
}

export interface CompleteVideoUploadResponse {
  videoId: string;
}

export const VIDEO_PACKAGE_NAME = "video";

export interface VideoServiceClient {
  verifyUploadedVideo(
    request: VerifyUploadedVideoRequest,
    metadata?: Metadata,
  ): Observable<VerifyUploadedVideoResponse>;

  getPostUpload(request: GetPostUploadRequest, metadata?: Metadata): Observable<GetPostUploadResponse>;

  completeVideoUpload(
    request: CompleteVideoUploadRequest,
    metadata?: Metadata,
  ): Observable<CompleteVideoUploadResponse>;
}

export interface VideoServiceController {
  verifyUploadedVideo(
    request: VerifyUploadedVideoRequest,
    metadata?: Metadata,
  ): Observable<VerifyUploadedVideoResponse>;

  getPostUpload(request: GetPostUploadRequest, metadata?: Metadata): Observable<GetPostUploadResponse>;

  completeVideoUpload(
    request: CompleteVideoUploadRequest,
    metadata?: Metadata,
  ): Observable<CompleteVideoUploadResponse>;
}

export function VideoServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["verifyUploadedVideo", "getPostUpload", "completeVideoUpload"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("VideoService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("VideoService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const VIDEO_SERVICE_NAME = "VideoService";
